"""empty message

Revision ID: 369befa9b817
Revises: 8b549b8a3182
Create Date: 2017-01-20 16:15:12.192126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369befa9b817'
down_revision = '8b549b8a3182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
